# Generated by Django 3.2.5 on 2021-09-03 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_bookmark_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_likes',
            field=models.ManyToManyField(related_name='Blog_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
